# Generated by Django 2.0.1 on 2018-10-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_input_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='input_option',
        ),
    ]
