# Generated by Django 2.0.1 on 2018-10-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_question_input_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='suffix',
        ),
    ]
