# Generated by Django 2.0.1 on 2018-10-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181019_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Input_Answer',
        ),
    ]
