# Generated by Django 2.0.1 on 2018-10-19 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_input_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_answer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='input_answer',
            name='name',
        ),
        migrations.AddField(
            model_name='input_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input_user',
            name='name',
            field=models.CharField(default='Stefan', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input_user',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Project'),
            preserve_default=False,
        ),
    ]
