# Generated by Django 2.0.1 on 2018-10-19 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=3, null=True)),
                ('prefix', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input_Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('is_writeable', models.BooleanField(default=True)),
                ('is_prefilled', models.IntegerField(blank=True, null=True)),
                ('decimal_scale', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)])),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hash_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('input_suffix', models.CharField(blank=True, max_length=3, null=True)),
                ('input_prefix', models.CharField(blank=True, max_length=3, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
            options={
                'ordering': ['project', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Question_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_short', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Question_Type'),
        ),
        migrations.AddField(
            model_name='input_title',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_title', to='main.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='input_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Input_Title'),
        ),
    ]
