# Generated by Django 2.0.1 on 2018-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181019_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='input',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
