# Generated by Django 2.0.1 on 2018-10-14 18:24

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_test_dvv_epensive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='basis_cheap',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='basis_epensive',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='basis_toocheap',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='basis_tooexpensive',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='dvv_cheap',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='dvv_epensive',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='dvv_toocheap',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='dvv_tooexpensive',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='exo_cheap',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='exo_epensive',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='exo_toocheap',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='exo_tooexpensive',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='plus_cheap',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='plus_epensive',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='plus_toocheap',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='answers',
            name='plus_tooexpensive',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
        migrations.AlterField(
            model_name='test',
            name='dvv_epensive',
            field=models.CharField(max_length=255, validators=[main.models.valid_pct]),
        ),
    ]
