# Generated by Django 2.0.1 on 2018-10-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181019_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(to='main.Input_Answer')),
            ],
        ),
    ]
