# Generated by Django 2.0.1 on 2018-10-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181019_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_answer',
            name='input',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='input_user',
            name='answer',
            field=models.ManyToManyField(related_name='fav', to='main.Input_Answer'),
        ),
    ]
