# Generated by Django 2.0.1 on 2018-10-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181021_2137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VWInputType',
            new_name='VW_Input_Type',
        ),
    ]
