# Generated by Django 2.0.1 on 2018-10-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181021_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vw_input_type',
            old_name='name_Short',
            new_name='name_short',
        ),
    ]
